# -*- coding: utf-8 -*-
"""calc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcLtoWz-Udt6d0TbeodhbUxcgVrsJyDe
"""

import streamlit as st

st.set_page_config(page_title="Rooftop Solar Sizing Calculator", page_icon="🔋")

st.title("🔋 Rooftop Solar Calculator (550W Panel Based)")
st.write("Estimate how many 550W solar panels you need based on your home's daily loads.")

st.markdown("---")

appliances = {
    "LED Bulbs (10W each)": 10,
    "Ceiling Fans (70W each)": 70,
    "Television (100W)": 100,
    "Refrigerator (150W)": 150,
    "Washing Machine (500W)": 500,
    "Mixer/Grinder (400W)": 400,
    "Laptop/Computer (100W)": 100,
    "WiFi Router (10W)": 10,
    "Air Conditioner 1.5 Ton (1500W)": 1500,
    "Geyser/Water Heater (2000W)": 2000,
    "Microwave (1200W)": 1200,
}

st.subheader("📥 Select Your Appliances")
total_wattage = 0

for appliance, watt in appliances.items():
    qty = st.number_input(f"{appliance}", min_value=0, max_value=10, value=0, step=1)
    total_wattage += qty * watt

# Custom Load
st.markdown("### ➕ Add Custom Load")
custom_qty = st.number_input("Quantity", min_value=0, max_value=10, value=0, step=1)
custom_watt = st.number_input("Wattage per item (W)", min_value=0, max_value=10000, value=0, step=50)
total_wattage += custom_qty * custom_watt

# Panel calculation
panel_wattage = 550
num_panels = round(total_wattage / panel_wattage + 0.4)
system_kw = num_panels * panel_wattage / 1000

# Electrical characteristics
voc_per_panel = 49.5
imp_per_panel = 13
total_voc = voc_per_panel * num_panels
mppt_current = imp_per_panel * num_panels

# Output Section
st.markdown("---")
st.subheader("📊 Your Solar Sizing Summary")
st.success(f"**Total Load**: {total_wattage} W")
st.info(f"**Recommended Number of 550W Panels**: {num_panels}")
st.write(f"**Estimated System Capacity**: {system_kw:.2f} kW")
st.write(f"**Total Voc (Open Circuit Voltage)**: ~{total_voc:.1f} V")
st.write(f"**MPPT Current Required**: ~{mppt_current:.1f} A")

if num_panels <= 9:
    st.success("✅ Single-MPPT String Inverter is suitable for this setup.")
else:
    st.warning("⚠️ Consider dual MPPT or higher-rated string inverters.")

st.markdown("---")
st.caption("Note: Always consult a certified installer to validate thermal limits, oversizing, and compatibility.")